### ISSUE TITLE
Nedetektuoja JOB DONE tago, purvinai veikia mygtukas Clear

### ISSUE THREAD

**Issue by Miceuz** [prospektai/plot-fork#2]
Nežinau, ar tai susiję bugai ar du atskiri, tai kolkas rašau viename tickete.

Dabar padariau 1s tarpus tarp `MEASUREMENT BEGIN` ir `MEASUREMENT END` - spalvos gulasi tvarkingai. Prieš `JOB DONE` mėginau palikti 2s tarpą, nepadeda.

Scenarijus:
- Paleisti ciklinę voltametriją
- Sulaukti pabaigos - JOB DONE eventas nedetektuojamas, nėra pranešimo konsolėje, STOP mygtukas lieka aktyvus
- Paspaudus STOP ir iš naujo paleidus sėkmingai paišo grafikus ant viršaus
- Paspaudus STOP, paspaudus CLEAR ir paspaudus RUN iškrenta exceptionas:
![image](https://github.com/prospektai/plot-fork/assets/533263/9b019c0b-2ab3-4fe4-a9c2-3d5c59fc1cf1)
- Tas pats exceptionas krenta kiekvieną kartą mėginant paleisti matavimą, kol perkraunamas puslapis

Taip pat kol vyksta matavimas CLEAR spaudymas gali išmesti exceptioną:
Scenarijus:
- Paleisti matavimą
- Spaudyti CLEAR, atsitiktinai išmeta exceptioną:
![image](https://github.com/prospektai/plot-fork/assets/533263/873239f1-17a8-4690-a0e5-a33c32dc6190)

**Comment by prospektai** [comment]
Bug 1 išsprendžiau, #JOB DONE turi būti aptinkamas automatiškai
Bug 2 galima išvengti neleidžiant naudotis Clear mygtuku, kol vykdomas matavimas. Šį sprendimą implementavau

e3d18f3

**Comment by Miceuz** [comment]
Puiku, veikia!
