### ISSUE TITLE
Disablinti RUN mygtuką, kai portas yra neatidarytas

### ISSUE THREAD

**Issue by Miceuz** [prospektai/plot-fork#3]
Dabar RUN mygtukas yra visada aktyvus, kol portas neatidarytas (ar buvo uždarytas dėl klaidos) nėra prasmės turėti mygtuką RUN enabliną.

**Comment by prospektai** [comment]
Run mygtukas išjungiamas jei nėra prisijungta prie įrenginio, taip pat jei nuskaitymo metu įvyksta klaida

+ 82f8c86 įdėtas pakeitimas "sulaukti" serial interface setup, jei tai dar nėra padaryta. Tai sprendžia situaciją kai pernelyg anksti paspaudus Run mygtuką niekas nevyksta.

**Comment by prospektai** [comment]
TESTOK
